version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./tools/postgres/data/pgdata:/var/lib/postgresql/data/pgdata"
      - "./tools/postgres/scripts:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: badpass
      POSTGRES_DB: mybookcollection
      PGDATA: /var/lib/postgresql/data/pgdata